jobs:
  - name: dataworks-aws-collections-rehydration-preprod
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: dataworks-aws-collections-rehydration
            trigger: true
            passed:
              - dataworks-aws-collections-rehydration-qa
          - get: emr-relauncher-release
            version: { tag: ((emr-relauncher-version.preprod)) }
            trigger: true
            passed:
              - dataworks-aws-collections-rehydration-qa
          - get: al2-emr-ami
            trigger: true
            passed:
              - dataworks-aws-collections-rehydration-qa
      - .: ((inject meta.plan.get-artefacts))
        config:
          params:
            launcher_version: ((emr_launcher_version.preprod)) 
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: preprod
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: preprod