jobs:
  - name: dataworks-aws-collections-rehydration-prod
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: dataworks-aws-collections-rehydration
            trigger: true
            passed:
              - dataworks-aws-collections-rehydration-preprod
          - get: emr-relauncher-release
            version: { tag: ((emr-relauncher-version.production)) }
            trigger: true
            passed:
            - dataworks-aws-collections-rehydration-preprod
          - get: al2-emr-ami
            trigger: true
            passed:
            - dataworks-aws-collections-rehydration-preprod
      - .: ((inject meta.plan.get-artefacts))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
            launcher_version: ((emr_launcher_version.production))
            emr_relauncher_ver: ((emr-relauncher-version.production))
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: production
          launcher_version: ((emr_launcher_version.production))
          emr_relauncher_ver: ((emr-relauncher-version.production))
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: production
          launcher_version: ((emr_launcher_version.production))
          emr_relauncher_ver: ((emr-relauncher-version.production))